name: argv
description: A sample arg parser for building CLI application followint the GNU and POSIX options style
version: 1.0.1
repository: https://github.com/marcomit/argv

environment:
  sdk: ^3.8.1

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.3
